// This file is generated by scripts/sync-blogs.mjs.
export const blogPosts = [
  {
    "title": "When Should Your Child See a Pediatric Pulmonologist?",
    "slug": "when-should-your-child-see-a-pediatric-pulmonologist",
    "description": "A checklist of symptoms and situations that may warrant a specialist evaluation.",
    "coverImage": "/images/blog/Cartoon pediatric pulmonologist examining a child with a parent in the room.jpg",
    "publishedAt": "2026-01-15",
    "updatedAt": "2026-01-15",
    "content": [
      {
        "type": "image",
        "alt": "Your Child's Lungs deserve the best care",
        "src": "/images/blog/Cartoon child with lungs.jpg"
      },
      {
        "type": "paragraph",
        "text": "Pediatric pulmonologists provide comprehensive evaluation and treatment of breathing and lung conditions in children."
      },
      {
        "type": "paragraph",
        "text": "Dr. Folashade Farri is a board-certified pediatric pulmonologist at CLAPS MD. Pediatric pulmonologists evaluate and treat conditions such as asthma, chronic cough, recurrent pneumonia, cystic fibrosis, sleep-related breathing disorders, stridor, upper airway obstruction, bronchopulmonary dysplasia (BPD), and other complex respiratory concerns."
      },
      {
        "type": "paragraph",
        "text": "Consider a specialist visit if your child has any of the following:"
      },
      {
        "type": "list",
        "items": [
          "Frequent need for albuterol (more than 2 times per week)",
          "Persistent asthma symptoms despite a maintenance regimen",
          "Hospital admission for asthma, especially more than once",
          "Needing oral steroids more than 2 times per year",
          "A diagnosis of asthma and you would like a second opinion",
          "Persistent cough associated with vomiting",
          "Cough with running, activity, or exercise",
          "Chronic or frequent respiratory infections",
          "Frequent or recurrent pneumonia (more than 1 confirmed pneumonia)",
          "Rapid, labored, or difficult breathing on a frequent basis",
          "Pauses or stopping breathing, especially while asleep",
          "Seeming overly tired during the day or overly hyperactive",
          "Positive newborn screen for cystic fibrosis",
          "Neuromuscular weakness or spasticity with drooling, choking, aspiration, or frequent pneumonia",
          "Sickle cell disease and frequent breathing problems or asthma",
          "Progressive scoliosis with breathing concerns"
        ]
      },
      {
        "type": "image",
        "alt": "We are here for you",
        "src": "/images/blog/cartoon-like image of a female, african-american, pediatric pulmonologist with a patient.jpg"
      },
      {
        "type": "paragraph",
        "text": "If you are unsure whether your child's symptoms require a specialist, we are happy to help guide you. Early evaluation can improve comfort, sleep, school performance, and overall quality of life."
      },
      {
        "type": "paragraph",
        "text": "Call our office or request an appointment online today."
      }
    ]
  },
  {
    "title": "Recognizing Asthma Symptoms in Your Child: What Parents Should Know",
    "slug": "recognizing-asthma-symptoms-in-your-child-what-parents-should-know",
    "description": "Learn the common warning signs of asthma in children and when to seek urgent care.",
    "coverImage": "/images/blog/generate a cartoon-like image of a parent taking care of her elementary-school age child who is coughing.jpg",
    "publishedAt": "2026-01-11",
    "updatedAt": "2026-01-11",
    "content": [
      {
        "type": "image",
        "alt": "Asthma symptoms can be very concerning",
        "src": "/images/blog/cartoon-like image of a child coughing.jpg"
      },
      {
        "type": "paragraph",
        "text": "Asthma is one of the most common chronic conditions in children. Early recognition of symptoms helps families get the right treatment plan and avoid emergencies."
      },
      {
        "type": "paragraph",
        "text": "Common symptoms include:"
      },
      {
        "type": "list",
        "items": [
          "Frequent coughing, especially at night or after activity",
          "Wheezing or a whistling sound when breathing",
          "Shortness of breath or rapid breathing",
          "Chest tightness or complaints of chest pain",
          "Fatigue during play or exercise"
        ]
      },
      {
        "type": "image",
        "alt": "Don't hesitate to schedule a visit",
        "src": "/images/blog/cartoon-like image of a female, african-american, pediatric pulmonologist with a patient.jpg"
      },
      {
        "type": "paragraph",
        "text": "Contact your pediatric pulmonologist if symptoms happen more than a couple of times per week, if rescue inhaler use increases, or if symptoms interfere with sleep or school."
      },
      {
        "type": "paragraph",
        "text": "Seek urgent care right away if your child is struggling to breathe, has persistent retractions (skin pulling in around the ribs or neck), or cannot speak in full sentences. When in doubt, call 911 or go to the nearest emergency department."
      },
      {
        "type": "paragraph",
        "text": "If you are unsure whether your child's symptoms require specialist care, we are happy to help you decide the next steps."
      }
    ]
  },
  {
    "title": "College-Bound with Asthma: Your Essential Preparation Guide",
    "slug": "college-bound-with-asthma-your-essential-preparation-guide",
    "description": "A practical checklist for students with asthma to prepare for a safe, healthy transition to college.",
    "coverImage": "/images/blog/ College-Bound Essentials.jpg",
    "publishedAt": "2025-09-04",
    "updatedAt": "2025-09-04",
    "content": [
      {
        "type": "image",
        "alt": "Good health ensures that College remains full of learning and fun",
        "src": "/images/blog/Cartoon-like image of Students on a College campus.jpg"
      },
      {
        "type": "paragraph",
        "text": "Starting college is an exciting milestone, but for students with asthma, preparation is key. A little planning goes a long way toward preventing flare-ups and avoiding missed classes."
      },
      {
        "type": "paragraph",
        "text": "Before you leave, review your asthma action plan with your pediatric pulmonologist. Make sure prescriptions are current and refills are easy to access."
      },
      {
        "type": "paragraph",
        "text": "Use this checklist to prepare:"
      },
      {
        "type": "list",
        "items": [
          "Pack controller and rescue inhalers, spacers, and any nebulizer supplies.",
          "Keep a copy of your asthma action plan with you and share it with a roommate.",
          "Identify the nearest campus health center and urgent care.",
          "Ask about dorm cleaning schedules, air filters, and potential triggers like mold or dust.",
          "Set reminders to take daily medications on time."
        ]
      },
      {
        "type": "image",
        "alt": "Let's get you all set to thrive in College",
        "src": "/images/blog/Cartoon-like image of College student going through checklist with Pediatrician who takes care of her.jpg"
      },
      {
        "type": "paragraph",
        "text": "If you notice increased symptoms after arriving on campus, schedule a telemedicine visit or contact our office. Early adjustments can help you stay on track all semester."
      }
    ]
  },
  {
    "title": "5 Pediatric Breathing Exercises That Actually Work",
    "slug": "5-pediatric-breathing-exercises-that-actually-work",
    "description": "Discover five simple breathing exercises that help children build lung strength and stay calm during flare-ups.",
    "coverImage": "/images/blog/pediatrician-with-child-and-parent.png",
    "publishedAt": "2025-08-12",
    "updatedAt": "2025-08-12",
    "content": [
      {
        "type": "image",
        "alt": "Breath like a Super hero!",
        "src": "/images/blog/super-hero-breathing.png"
      },
      {
        "type": "paragraph",
        "text": "At C.L.A.P.S. MD, we believe that education is the key to healthy lungs. Whether your child struggles with asthma, anxiety, or chronic cough, breathing exercises can be a powerful (and playful) tool for daily support."
      },
      {
        "type": "paragraph",
        "text": "Below are five simple techniques to try at home. These can be practiced during calm moments, so children feel confident using them when symptoms flare."
      },
      {
        "type": "paragraph",
        "text": "1. Belly breathing Place a hand on the belly and one on the chest. Breathe in slowly through the nose so the belly rises, then exhale gently through the mouth."
      },
      {
        "type": "paragraph",
        "text": "2. Bubble breathing Blow bubbles slowly and steadily. The long, controlled exhale helps reduce shortness of breath and encourages relaxed breathing."
      },
      {
        "type": "image",
        "alt": "Ballon Breathing",
        "src": "/images/blog/bubble-breathing.png"
      },
      {
        "type": "paragraph",
        "text": "3. Pursed-lip breathing Breathe in through the nose for two counts and exhale through pursed lips for four counts. This slows breathing and helps keep airways open longer."
      },
      {
        "type": "paragraph",
        "text": "4. Teddy bear breathing Have your child lie down with a small stuffed animal on the belly and watch it rise and fall with each breath."
      },
      {
        "type": "paragraph",
        "text": "5. Box breathing Inhale for four counts, hold for four, exhale for four, and hold for four. Repeat a few cycles to reset breathing and calm the body."
      },
      {
        "type": "paragraph",
        "text": "If your child has frequent symptoms or needs rescue medication often, please contact our office to review their asthma action plan."
      }
    ]
  }
];

export function getBlogPostBySlug(slug) {
  if (!slug) return null;
  return blogPosts.find((post) => post.slug.toLowerCase() === slug.toLowerCase());
}
